apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::818193600336:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-L9WX2XDUGLIR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-02T22:10:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "816"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 184beba4-f97d-4651-9d38-3ee8f62cd8d7
